# Generated by Django 5.2 on 2025-04-16 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=256, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('business_weight', models.FloatField(default=0.0)),
                ('sports_weight', models.FloatField(default=0.0)),
                ('technology_weight', models.FloatField(default=0.0)),
                ('entertainment_weight', models.FloatField(default=0.0)),
                ('health_weight', models.FloatField(default=0.0)),
                ('general_weight', models.FloatField(default=0.0)),
                ('science_weight', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('clicked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('news_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsarticle')),
            ],
        ),
    ]
